### DISCUSSION TITLE
Macos style launchpad

### DISCUSSION THREAD

**Discussion by AYA-123** [amnweb/yasb#152] [Q&A] [answered]
In the komorebi showcase video for the theme yasb 003, clicking the top left icon causes a macos-like launchpad to come up. I was wondering how it was achieved, because it looks so good! I am using komorebi, but still it doesn't work for some reason.

![image](https://github.com/user-attachments/assets/9d292642-6cb5-4b33-9731-95eb8070f3f7)
Thanks for any help

**Comment by amnweb** [comment]
https://winlaunch.org/

https://github.com/jensroth-git/WinLaunch

**Reply by AYA-123** [reply]
Thanks for the links - is it possible to tell me how to modify 
```
  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue62a"
      label_alt: "\ue62a"
      class_name: "win-button-widget"
      callbacks:
        on_left: "exec start_menu"
``` 
to use winlaunch - yasb is very cool, but I'm not really sure how to do this?
