### DISCUSSION TITLE
Some questions about configurations

### DISCUSSION THREAD

**Discussion by bytenekos** [amnweb/yasb#17] [Q&A] [answered]
Hi there! I'm pretty new to the world of TWMs and status bars (especially on windows lol) so forgive me if this is a simple question:

How do you round certain parts of the top bar?
For example I can't figure out where I'd adjust the css so that I can round the windows button thingy, same thing for the language thingy

![image](https://github.com/user-attachments/assets/71ada582-3cea-47a4-8646-50543a993278)
![image](https://github.com/user-attachments/assets/efe241de-c3ae-4160-b45c-8dc1fb364c1b)

I want these rounded, but can't find where/how I'd do so, so would love some help :D

Another question is how can I (if possible) have different top bars per monitor (I have a regular main monitor and a vertical second monitor, so I'd like the second monitor to have some different stuff on it)?

**Comment by amnweb** [comment, marked as answer]
For language widget you can try something like  
```
.lang-widget .widget-container {
	background-color: #313244;
	margin: 4px 0 4px 0;
	border-radius: 14px;
}
```

Yes you can have different bar on each monitor. 

example

```
bars:
  status-bar1:
    enabled: true
    screens: ['DELL P2419H (1)'] 
   ...
  status-bar2:
    enabled: true
    screens: ['DELL P2419H (2)'] 
   ...
```
