### DISCUSSION TITLE
How to correctly set weather location to env?

### DISCUSSION THREAD

**Discussion by l-ngph-m** [amnweb/yasb#175] [Q&A] [answered]
Hey yall I'm trying to configure my weather widget to dynamically update my location. 

I managed to hack together a cmd script that sets the `YASB_WEATHER_LOCATION` environment variable to my coordinates (which I can confirm does work with the widget when set in `config.yaml`). 

But the problem now is I don't know how to set the widget's location to use the env variable in `config.yaml`, as per the documentation. 
I have tried
```yaml
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      location: env
```
and manually setting `YASB_WEATHER_LOCATION` in `System Properties` to both the full `{COUNTRY CITY ZIP_CODE}` and coordinates, with and without quotation marks "" and it still wouldn't work.

Any help would be appreciated.

**Comment by amnweb** [comment, marked as answer]
Something like this
![image](https://github.com/user-attachments/assets/aba9af00-35eb-430e-8357-df62ed4b18ff)

But keep in mind, you are using Windows. Sometimes, the OS won't reload the ENV without a restart :(

**Reply by l-ngph-m** [reply]
A reboot fixed it, thanks for the reply. 

This is the cmd script to set the variable on Windows if anyone is interested. I just have a shortcut of it in the `shell:startup` folder. Thought this might be useful since I move around a lot. 

```cmd
@echo off
setlocal enabledelayedexpansion
for /f "tokens=2 delims=:" %%i in ('curl -s http://ipinfo.io/json ^| findstr "loc"') do (
    set location=%%i
    set location=!location:~0,-1!
    setx YASB_WEATHER_LOCATION !location!
)
endlocal
```

**Reply by amnweb** [reply]
From version 1.6.7 you can use variable like `$env:VARIABLE_NAME`

```
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      location: "$env:MY_LOCATION"
```

Also, YASB can now read variables from a file
`env_file: ".env"`
