### DISCUSSION TITLE
How to line feed the clock time format

### DISCUSSION THREAD

**Discussion by Sighthesia** [amnweb/yasb#209] [Q&A] [answered]
![QQ20250417-165431](https://github.com/user-attachments/assets/d53cdf34-da99-41aa-9541-aa48fff648d8)
I tried to use "\n" to line feed the time format in config.yaml to save space
```yaml
clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{\udb83\ude18 %Y.%m.%d \n \uf017 %H:%M:%S}"
      label_alt: "{%A, %B %d %Y %H:%M}"
      timezones: []
      callbacks:
        on_left: "toggle_label"
```
but in vaild as the clock failed to work, displaying the time format directly
![QQ20250417-165835](https://github.com/user-attachments/assets/90d19df2-1405-406d-87ee-6e295dd1d259)
I don't know if the widget support line feed or not, or is there another way to line feed?
