### DISCUSSION TITLE
Multiple Monitors/Disks, Ethernet, and Discord. Questions!

### DISCUSSION THREAD

**Discussion by y0himba** [amnweb/yasb#28] [Q&A]
I have questions:

1: I have multiple disks. I have tried copy/paste changing the labels and `on_click`. I have tried enumerating the disks as below. YASB will not start when I add them.  I have C/D/E/F/H/I. Two HDD for storage and the rest are SSD/nVME.  (I am an old gamer) What am I doing wrong?

2: I have 2 monitors.  Do I need to run and configure separate instances of YASB?  I'd like time/weather/media on monitor 1 and system info on monitor 2.

3: It is not detecting my ethernet connection. `Killer E3100G 2.5 Gigabit Ethernet Controller` 
![image](https://github.com/user-attachments/assets/d41edfff-921e-4910-8d78-20dfeb979387)

4: It there a Discord?  I love this toolbar beyond belief. It replaced Rainmeter. 

```
disk1:
    type: "yasb.disk.DiskWidget"
    options:
        label: "{volume_label} {space[used][percent]}"
        label_alt: "{volume_label} {space[used][gb]} / {space[total][gb]}"
        volume_label: "D"
        update_interval: 60 # Update interval in seconds
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec explorer D:\\" # Open disk C in file explorer

disk2:
    type: "yasb.disk.DiskWidget"
    options:
        label: "{volume_label} {space[used][percent]}"
        label_alt: "{volume_label} {space[used][gb]} / {space[total][gb]}"
        volume_label: "E"
        update_interval: 60 # Update interval in seconds
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec explorer E:\\" # Open disk C in file explorer

disk3:
    type: "yasb.disk.DiskWidget"
    options:
        label: "{volume_label} {space[used][percent]}"
        label_alt: "{volume_label} {space[used][gb]} / {space[total][gb]}"
        volume_label: "F"
        update_interval: 60 # Update interval in seconds
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec explorer F:\\" # Open disk C in file explorer

disk4:
    type: "yasb.disk.DiskWidget"
    options:
        label: "{volume_label} {space[used][percent]}"
        label_alt: "{volume_label} {space[used][gb]} / {space[total][gb]}"
        volume_label: "H"
        update_interval: 60 # Update interval in seconds
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec explorer H:\\" # Open disk C in file explorer

disk5:
    type: "yasb.disk.DiskWidget"
    options:
        label: "{volume_label} {space[used][percent]}"
        label_alt: "{volume_label} {space[used][gb]} / {space[total][gb]}"
        volume_label: "I"
        update_interval: 60 # Update interval in seconds
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec explorer I:\\" # Open disk C in file explorer

disk6:
    type: "yasb.disk.DiskWidget"
    options:
        label: "{volume_label} {space[used][percent]}"
        label_alt: "{volume_label} {space[used][gb]} / {space[total][gb]}"
        volume_label: "J"
        update_interval: 60 # Update interval in seconds
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec explorer J:\\" # Open disk C in file explorer
```
