### DISCUSSION TITLE
Displaying a measurement through another widget possible?

### DISCUSSION THREAD

**Discussion by Slim08** [amnweb/yasb#78] [Q&A] [answered]
Is there a way of pulling a measurement from one widget and displaying it through another widget?
My case specifically:

```
  # TRAFFIC WIDGET
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\uf019 {download_speed} \uf093 {upload_speed}</span>"
      label_alt: "<span>\uf019 {download_speed} \uf093 {upload_speed}</span>"
      update_interval: 1000
      
  # IP ADDRESS WIDGET
  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\udb82\ude60 {data[ip]}"
      label_alt: "\udb82\ude60 [Hidden]"
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000                                       # every 5 minutes
        return_format: "json"
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl"                          # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]}" # open ipinfo in browser
```
I'd like to get the "{data[ip]}" measurement as the alternative label in the traffic widget displayed. Is that possible?
