### DISCUSSION TITLE
Translating right click to pause button press on volume widget

### DISCUSSION THREAD

**Discussion by Slim08** [amnweb/yasb#79] [Q&A] [answered]
I have EarTrumpet for my Windows sound mixer menu installed and would like to open its flyout menu rather than the Windows sound settings window. Since the EarTrumpet dev doesn't seem too keen on supporting other apps interfacing with his, direct command line control isn't an option. But I can bind hotkeys in EarTrumpet to perform the desired action. I bound it in my case to the "PAUSE" button.

```
  # VOLUME WIDGET
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>{level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
```

How would I translate the "RIGHT MOUSE BUTTON" click on the volume widget to a "PAUSE" button press?
