### DISCUSSION TITLE
Is it possible to nest elements in a label?

### DISCUSSION THREAD

**Discussion by holty07** [amnweb/yasb#84] [Q&A] [answered]
Below is my current traffic widget but it is displaying incorrectly.

~~~
traffic:
      type: "yasb.traffic.TrafficWidget"
      options:
        label: "<span class=\"traf\">D: <span class=\"speed\">{download_speed}</span></span><span class=\"traf\">U: <span class=\"speed\">{upload_speed}</span></span>"
        label_alt: "Download {download_speed} \ue621 Upload {upload_speed}"
        update_interval: 1000 # Update interval should be a multiple of 1000
        callbacks:
          on_left: "toggle_label"
          on_right: "exec cmd /c Taskmgr"
~~~
![image](https://github.com/user-attachments/assets/06213b7a-ed87-420d-82fd-ce0bdc98b602)

**Comment by amnweb** [comment]
I'm not sure that is possible in this way, maybe you can try with inline style directly in config, but do not use span because span is reserved for icons. And what result do you expect? How should this widget look at the end?

**Reply by holty07** [reply]
Perfect this has almost done what I want now. I have included right text align inline now. Is it possible to also give my divs a width? I am trying to avoid my media widget jumping around because my speed is dynamic.
```
traffic:
      type: "yasb.traffic.TrafficWidget"
      options:
        label: "<div style=\"text-align:right; width:300px;\">U: {upload_speed}</div><div style=\"text-align:right;\">D: {download_speed}</div>"
        label_alt: "Download: {download_speed} | Upload: {upload_speed}"
        update_interval: 1000 # Update interval should be a multiple of 1000
        callbacks:
          on_left: "toggle_label"
          on_right: "exec cmd /c Taskmgr"
```
![image](https://github.com/user-attachments/assets/4132a1a4-4070-4a2f-a2a7-b9b07145f384)
