### ISSUE TITLE
using Fahrenheit in the weather widget doesn't work.

### ISSUE THREAD

**Issue by azinsharaf** [amnweb/yasb#109]
**Describe the bug**
using Fahrenheit in the weather widget doesn't work.

**To Reproduce**
use the following code in the `config.yaml`:
```
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp_f}"
      label_alt: "{location}: Min {min_temp_f}, Max {max_temp_f}, Humidity {humidity}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807"
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: "Oakland, CA"
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzard: "\uebaa"
        default: "\uebaa"
        # https://www.weatherapi.com/docs/
        # Usage {temp}, {min_temp}, {max_temp}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/db9cca30-53f7-4662-9827-217c7ba4716b)

**Desktop (please complete the following information):**
 - OS: `Windows 11 Pro 24H2`
 - Browser `Zen`
 - YASB branch `main` `1.5.4`
 - Python `3.12.8`
