### ISSUE TITLE
Hide traffic widget if it's below specified threshold or not connected to network

### ISSUE THREAD

**Issue by mizzunet** [amnweb/yasb#129]
**What is the request?.**
Hide traffic widget if it's below specified threshold or not connected to network

**Why is it useful?**
Clean look. Such widget won't be useful when shown without network

**How could it be implemented?**
Config could be
```
traffic:
    options:
        hide_if_offline: true
        minimum_threshold: 10240KB
...
```
On value updating, check if
1. Network has been disconnected
2. If the transfer is below the threshold

**Additional context**
Thanks :)
