### ISSUE TITLE
Bar doesn't render properly anymore

### ISSUE THREAD

**Issue by Kazuto** [amnweb/yasb#132]
**Describe the bug**
Since yesterday the bar just gets cut off after the first workspace. 

**To Reproduce**

**Expected behavior**
The bar is rendered properly

**Screenshots**

![Image](https://github.com/user-attachments/assets/91ce4f3c-0bdd-4aa1-b285-5e82f898cb08)

**Desktop (please complete the following information):**
 - OS: Windows 11 22631
 - Browser: Thorium
 - YASB branch: main
 - Python 3.10.11

**Additional context**
```
2025-02-01 09:42:32 INFO log.py:21: Yasb
2025-02-01 09:42:32 INFO main.py:23: Debug mode enabled.
2025-02-01 09:42:33 DEBUG media.py:103: MediaCallback: _on_current_session_changed
2025-02-01 09:42:33 INFO github.py:292: Check for GitHub notifications at 2025-02-01 09:42:33.313770
2025-02-01 09:42:33 INFO weather.py:156: Fetched new weather data at 2025-02-01 09:42:33.392084
2025-02-01 09:42:33 DEBUG __init__.py:143: CoInitializeEx(None, 2)
2025-02-01 09:42:33 INFO event_listener.py:52: Created named pipe yasb-7b1c08ae-e078-11ef-a7bf-f889d2da94dc
2025-02-01 09:42:33 INFO event_listener.py:106: Waiting for Komorebi to subscribe to named pipe yasb-7b1c08ae-e078-11ef-a7bf-f889d2da94dc
2025-02-01 09:42:33 INFO watcher.py:39: Created file watcher for path C:\Users\Kazuto\.config\yasb
2025-02-01 09:42:33 DEBUG _windows.py:213: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-02-01 09:42:33 DEBUG _windows.py:192: Thread started
2025-02-01 09:42:33 DEBUG media.py:103: MediaCallback: _on_current_session_changed
2025-02-01 09:42:33 INFO media.py:127: MediaCallback: _on_playback_info_changed
2025-02-01 09:42:33 INFO media.py:141: MediaCallback: _on_timeline_properties_changed
2025-02-01 09:42:33 DEBUG media.py:155: MediaCallback: _on_media_properties_changed
2025-02-01 09:42:33 DEBUG media.py:167: MediaCallback: Attempting media info update
2025-02-01 09:42:33 INFO event_listener.py:118: Komorebi connected to named pipe: yasb-7b1c08ae-e078-11ef-a7bf-f889d2da94dc
2025-02-01 09:42:33 DEBUG media.py:196: MediaCallback: Media info update finished
```

```yaml
watch_stylesheet: true
watch_config: true
debug: true # Enable debug mode to see more logs

# This komorebi setting will be used for tray context menu.
# If you don't use komorebi, you can remove this section.
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"
  
# This is the main configuration file for Yet Another Status Bar (YASB)
bars:
  status-bar:
    enabled: true
    #screens: ['DELL P2419H (1)'] # If you want to show on specific screen
    screens: ['G34WQC A'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false # Blur effect will be applied to the bar
      acrylic: false # Acrylic effect will be applied to the bar
      dark_mode: false # Dark mode will add more shadow to the bar
      round_corners: false # Default radius from OS
      border_color: System # None, System or HEX color (this option is related to round_corners=true)
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 4
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        [
          "komorebi_workspaces",
          "active_window"
        ] 
      center: [
          "apps",
        ]
      right:
        [
          "media",
          "github",
          "clock",
          "weather",
          "volume",
          "power_menu",
        ]

widgets:
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - {icon: "\uf268", launch: "C:\\Users\\Kazuto\\AppData\\Local\\Thorium\\Application\\thorium.exe"}
        - {icon: "\uf1ff", launch: "C:\\Users\\Kazuto\\AppData\\Local\\Discord\\Update.exe"}
        - {icon: "\udb81\ude87", launch: "C:\\Users\\Kazuto\\AppData\\Local\\Mailspring\\mailspring.exe"}
        - {icon: "\uf2c6", launch: "C:\\Users\\Kazuto\\AppData\\Roaming\\Telegram Desktop\\Telegram.exe"}
        - {icon: "\udb81\udcc7", launch: "C:\\Users\\Kazuto\\AppData\\Roaming\\Spotify\\Spotify.exe"}
        - {icon: "\udb82\ude1e", launch: "C:\\Users\\Kazuto\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe"}

  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "{volume_label} {space[used][percent]}"
        label_alt: "{volume_label} {space[used][gb]} / {space[total][gb]}"
        volume_label: "C"
        update_interval: 60 # Update interval in seconds
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec explorer C:\\" # Open disk C in file explorer

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: "{title}"
      max_field_size:
        label: 55
        label_alt: 20
      show_thumbnail: true
      controls_only: false
      controls_left: true
      hide_empty: false
      thumbnail_alpha: 50
      thumbnail_padding: 26
      thumbnail_corner_radius: 0 # Set to 0 for square corners
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0d"
        pause: "\udb80\udfe6"

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "{win[title]}"
      #label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 12
      max_length: 28
      max_length_ellipsis: "..."
      monitor_exclusive: true

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d, %b %H:%M}"
      label_alt: "{%A %d %B %Y, %H:%M}"
      #locale: 'en_EN' # Langugae for date, you can set your own, example fr_FR
      timezones: ["Europe/Berlin"] #Looking up time zone info from registry
      #timezones: ["America/Montreal"]

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> {virtual_mem_percent}%"
      label_alt: "<span>\uf4bc</span> {virtual_mem_free}"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "<span>\uf1ab</span> {lang[language_code]}-{lang[country_code]}"
      label_alt: " {lang[full_name]}"
      update_interval: 5 # 5 seconds
      callbacks:
        on_left: "toggle_label"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "{name}"
        label_workspace_active_btn: "{name}"
        label_workspace_populated_btn: "{name}"
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false
        hide_if_offline: false
        animation: false
        container_padding:
          top: 0
          left: 8
          bottom: 0
          right: 8

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:network"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\udb86\uddb3</span>{download_speed} | <span>\udb86\uddb2</span>{upload_speed}"
      label_alt: "Download {download_speed} \ue621 Upload {upload_speed}"
      update_interval: 1000 # Update interval should be a multiple of 1000
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd /c Taskmgr"

  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\udb81\udd9f</span> {data[ip]}"
      label_alt: "<span>\uf450</span> {data[city]} {data[region]}, {data[country]}"
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000  # every 5 minutes
        return_format: "json"
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl" # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp_c}"
      label_alt: "Min {min_temp_c}, Max {max_temp_c}, Humidity {humidity}"
      api_key: '' # Get your free API key from https://www.weatherapi.com/
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: 'Germany 41065' # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_label"
      icons: 
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzard: "\uebaa"
        default: "\uebaa"
        # https://www.weatherapi.com/docs/
        # Usage {temp_c}, {min_temp_c}, {max_temp_c}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300 # Milisecond 
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\uea75","Lock"]
        signout: ["\udb80\udf43","Sign out"]
        #sleep: ["\u23fe","Sleep"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        hibernate: ["\uf28e","Hibernate"]
        cancel: ["\udb81\udf3a","Cancel"]
        #force_shutdown: ["\uf011","Force Shut Down"]
        #force_restart: ["\uead2","Force Restart"]

  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}" # {data} return number of unread notification
      token: # GitHub Personal access tokens (classic) https://github.com/settings/tokens
      # You can set token: env, this means you have to set YASB_GITHUB_TOKEN in environment variable
      max_notification: 20 # Max number of notification displaying in menu max: 50
      only_unread: false # Show only unread or all notifications; 
      max_field_size: 54 # Max characters in title before truncation.
      menu_width: 400 
      menu_height: 400 
      menu_offset: 240 
      update_interval: 300 # Check for new notification in seconds

  wallapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\xxx\\Images" # Path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation: false
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  nvidia_temp:
    type: "yasb.custom.CustomWidget"
    options:
      label: "{data}<span>\udb81\udd04</span>"
      label_alt: "{data}"
      class_name: "system-widget"
      exec_options:
        run_cmd: "powershell nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader"
        run_interval: 10000 # run every 10 sec
        return_format: "string"

  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue62a"
      label_alt: "\ue62a"
      class_name: "system-widget"
      callbacks:
        on_left: "exec start_menu"
```
