### ISSUE TITLE
`controls_hide` option in Media widget doesn't work

### ISSUE THREAD

**Issue by kkanden** [amnweb/yasb#165]
### Windows version

Windows 11

### Windows OS build

26100.3476

### YASB installed or from source

Installed

### Python Version

3.12.9

### YASB version installed

1.6.6

### Describe the bug

When setting the `controls_hide` option of the Media widget to true in the config file, an error "Failed to validate widget(s) due to invalid options" occurs.

Relevant config.yaml part:
```yaml
    media:
        type: "yasb.media.MediaWidget"
        options:
            label: "{artist} - {title}"
            label_alt: "<span>\uf001</span> {artist} - {title}"
            hide_empty: true
            max_field_size:
                label: 20
            show_thumbnail: true
            controls_only: false
            controls_left: true
            controls_hide: true
            thumbnail_alpha: 50
            thumbnail_padding: 70
            thumbnail_corner_radius: 12
            icons:
                prev_track: "\ue892"
                next_track: "\ue893"
                play: "\ue768"
                pause: "\ue769"
            callbacks:
                on_left: "do_nothing"
```

### Relevant log output

```shell
2025-03-20 18:49:52 ERROR widget_builder.py:88: Failed to validate widget(s) due to invalid options  - media
      controls_hide:
      - unknown field
```
