### ISSUE TITLE
Improve Language Widget

### ISSUE THREAD

**Issue by xmha97** [amnweb/yasb#185]
### What is the request?

Please improve the language widget.
1. I need a "Language Menu".
2. Also I want to switch language quickly using right click.
```yaml
callbacks:
    on_left: "toggle_language_menu"
    on_middle: "do_nothing"
    on_right: "switch_language"
```

### Why is it useful?

![Image](https://github.com/user-attachments/assets/8504c945-4bcb-403a-a316-968f3741e4e8)

![Image](https://github.com/user-attachments/assets/ae10a5fb-c965-4a2c-9d1d-c251af521413)
