### ISSUE TITLE
Show apps pinned to the Windows taskbar

### ISSUE THREAD

**Issue by ykhan21** [amnweb/yasb#194]
### What is the request?

Include apps pinned to the Windows taskbar in the Application widget.

### Why is it useful?

It is helpful to users coming into yasb. They wont have to find an icon for each of their apps for the widget (https://github.com/amnweb/yasb/wiki/(Widget)-Applications).

### How could it be implemented?

Add a boolean flag like so.
The icons to these apps should be the same icons found on the Windows taskbar.
The list of pinned apps is here: `%AppData%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar`.

```yaml
apps:
  type: "yasb.applications.ApplicationsWidget"
  options:
    label: "{data}"
    include_pinned_windows_taskbar_apps: true
    app_list:
      - {icon: "\uf0a2", launch: "notification_center"} # launch notification center
      - {icon: "\ueb51", launch: "quick_settings"} # launch quick settings
...
```
