### ISSUE TITLE
Default background behind the bar.

### ISSUE THREAD

**Issue by FlyinCow** [amnweb/yasb#2]
I'm trying to make a nice rounded-corner bar while I find there's a default background. It only appears with blur effect on.
style.css:
```css
.bar {
  background-color: rgba(255, 255, 255, 1); // only to make it more clear
  padding: 0 8px;
  border-radius: 8px;
}
```
With `bars.blur_effect.enabled=true` and `bars.blur_effect.arcylic=true` in config.yaml:
![image](https://github.com/amnweb/yasb/assets/23637371/7798b5f4-d826-49c2-b69e-c81f5aa6e369)

With `bars.blur_effect.enabled=true` but`bars.blur_effect.arcylic=false`:
![image](https://github.com/amnweb/yasb/assets/23637371/56c82d6f-632e-41c8-8a59-93b71c567891)

With `bar.blur_effect.enabled=false` it will disappear:
![image](https://github.com/amnweb/yasb/assets/23637371/293980bc-ff9d-40eb-89f8-01a0e74684f1)

There may be something to do with PyQT itself. Rather removing this background or making a `bar.border` option with will be generous.

BTW is this bar just a PyQT window at all? Maybe I will learn to fix it myself.
