### ISSUE TITLE
Hide CustomWidget if the label is empty

### ISSUE THREAD

**Issue by weiest** [amnweb/yasb#39]
**What is the request?.**
The ability to add a flag for `yasb.custom.CustomWidget` that will stop the rendering of an empty label (e.g. `{data}`).

**Why is it useful?**
This feature would be useful for people to create custom widgets that gets status of running processes in the system, look at example use cases below. This could be useful to only show up if something is wrong..

**How could it be implemented?**
consider a `hide_if_empty` to `yasb.custom.CustomWidget` so that if the label is empty, it hides/not show it.

**Additional context**
I decided to create a function to show if any process/services is not running in the background, e.g. iCue using the following code.
```yaml
  icue_service_check:
      type: "yasb.custom.CustomWidget"
      options:
        label: "{data}"
        label_alt: "{data}"
        class_name: "system-widget icue-service-check"
        exec_options:
          run_cmd: "powershell IF($(Get-Process -name iCue -ErrorAction SilentlyContinue) -eq $null) {'Not Running'} ELSE {'OK'}"
          run_interval: 60000
          return_format: "string"
        callbacks:
          on_right: "do_nothing"
          on_left: "do_nothing"
```
If the ELSE condition on the run_cmd line is changed from 'OK' to ''; {data} will return nothing and there will be a empty box (depends on your styles.css)

**Comment by amnweb** [comment]
I just tried it and for me it's working fine.
```
  exec_options:
    run_cmd: "powershell IF($(Get-Process -name firefox -ErrorAction SilentlyContinue) -eq $null) {'Not Running'} ELSE {'OK'}"
    return_format: "string"
    run_interval: 3000
```
https://github.com/user-attachments/assets/fe993f9c-876b-4e19-b74c-7dee573ec61b
