### ISSUE TITLE
Custom Widget doesn't appear when started with AutoHotkey

### ISSUE THREAD

**Issue by Coelhomatias** [amnweb/yasb#83]
**Describe the bug**
A custom widget I configured to display the currently focused komorebi workspace does not appear on the bar when initiated through an AutoHotkey script. I have verified that komorebi is launched before yasb.

**To Reproduce**
1. Add custom widget to config, don't forget to add it to the widgets field:
	```yaml
	nvidia_temp:
	    type: "yasb.custom.CustomWidget"
	    options:
	      label: "{data}"
	      label_alt: "{data}"
	      class_name: "system-widget"
	      exec_options:
	        run_cmd: "powershell . .\\workspace_name.ps1"
	        run_interval: 1000
	        return_format: "string"
	        hide_empty: false
	```
2. Create `workspace_name.ps1` file in the same directory as config:
	```powershell
	# Retrieve the focused workspace and monitor indices
	$workspace_idx = [int](komorebic.exe query focused-workspace-index)
	$monitor_idx = [int](komorebic.exe query focused-monitor-index)
	
	# Retrieve the state as JSON, convert it to a PowerShell object
	$state = komorebic.exe state | ConvertFrom-Json
	return $state.monitors.elements[$monitor_idx].workspaces.elements[$workspace_idx].name
	```
3. Run yasb within an AutoHotkey V2 script with:
	```ahk
	if !ProcessExist("yasbc.exe") {
    	RunWait("yasbc.exe start", , "Hide")
	}
	```
4. See error. Custom widget does not appear on the bar,

**Expected behavior**
The custom widget should appear on the bar.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.26100.2605] (Windows 11 Home)
 - Browser: edge
 - YASB branch main
 - Python 3.12

**Additional context**
If the bar is subsequently stopped and restarted using the command line, it functions correctly.
